# Generated by Django 2.2.7 on 2019-11-29 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0004_auto_20191128_1014"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="tls_client_certificate_bound_access_tokens",
            field=models.BooleanField(
                default=False,
                verbose_name="Bind Access Tokens to TLS Client Certificate",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="tls_certificate",
            field=models.TextField(
                blank=True, verbose_name="TLS Certificate to bind the access token to"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="redirect_uris",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="tls_certificate",
            field=models.TextField(
                blank=True,
                help_text="Only used if token_endpoint_auth_method is self_signed_tls_client_auth.",
                verbose_name="TLS Certificate",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="token_endpoint_auth_method",
            field=models.CharField(
                choices=[
                    (
                        "client_secret_basic",
                        "Client secret contained in Basic Authorization header",
                    ),
                    (
                        "client_secret_post",
                        "Client secret contained in form post parameters.",
                    ),
                    (
                        "tls_client_auth",
                        "Mutual TLS with PKI certificates (NOT IMPLEMENTED)",
                    ),
                    (
                        "self_signed_tls_client_auth",
                        "Mutual TLS with a self-signed certificate",
                    ),
                ],
                help_text="Used at the token endpoint and the pushed authorization request endpoint.",
                max_length=128,
                verbose_name="Client authentication method",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="pkce_required",
            field=models.BooleanField(default=True, verbose_name="PKCE required"),
        ),
        migrations.AlterField(
            model_name="session",
            name="scope",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), blank=True, size=None
            ),
        ),
    ]
